on:
  push:
    branches: [main]
    paths: commit.txt

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: |
          previous=$(git --no-pager show HEAD~1:commit.txt)
          current=$(git --no-pager show HEAD:commit.txt)
          printf 'before:%s\ncurrent:%s\n' $previous $current
      - run: |
          echo $previous
          echo $current
