on:
  push:
    branches: [main]
    paths: commit.txt

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          printf 'before:%s\ncurrent:%s\n' \
            $(git --no-pager show HEAD~1:commit.txt) \
            $(git --no-pager show HEAD:commit.txt)
